### ISSUE TITLE
Вопрос по скорости выполнения

### ISSUE THREAD

**Issue by Artyom16RUS** [Artyom16RUS/IO#1]
Первый способ, чтение данных через _BufferedInputStream_, а в другом способе создаем массив и указываем в методе _read()_ размер буфера. Подскажите, может знаете почему второй способ записи работает быстрее?  Проваливался в методы не особо понял. Документации тоже не выяснил.

**Comment by coursar** [comment]
Потому что:
1. Так не меряют - нужно провести несколько тысяч итераций чтения и вычислить среднее
2. С BufferedReader'ом вы запрашиваете по одному байту - в итоге каждый раз тратится время на проверки и всё остальное. Если будете запрашивать не по одному, а по столько же, результаты будут сопосотавимы.
